# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
    -   id: add-trailing-comma

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.2
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: linting
        name: Check lint
        entry: make lint
        language: system
        pass_filenames: false
        types: [ python ]

      - id: pytest
        name: pytest
        entry: make test
        language: system
        pass_filenames: false
        types: [ python ]
